### ISSUE TITLE
你干嘛不自己部署一个网页到github 使用cloudflare.com的workers-and-pages

### ISSUE THREAD

**Issue by hestiacn** [msyuan/vitePress-project#5]
你干嘛不自己部署一个网页到github 使用cloudflare.com的workers-and-pages   要使用掘金。 而且还可以自由添加美化，网站样式。除了域名花钱，根本不要服务器啊  你在本地提交更改后到github自动推送到cloudflare。简直不要太舒服！

**Comment by msyuan** [comment]
@hestiacn cloudflare还是第一次知道，可以尝试，做个人博客服务器花了不少钱真不值得！

**Comment by hestiacn** [comment]
如果需要我可以教你。

https://yiov.top 像这个，它就更新了很多实用的文档。

https://github.com/eryajf 他有不少仓库资源 希望你可以用上

https://theme.sugarat.top 还有这个

**Comment by hestiacn** [comment]
来来来 我教你！
先去https://dash.cloudflare.com 注册个账号！如果打不开多刷新几次，别急！登录以后最好吧域名的DNS更改为cloudflare.com的，这样你不用去解析，自动解析。
弄好以后点击右上角的个人配置文件，点击新建api令牌，按照以下配置选择！

![Image](https://github.com/user-attachments/assets/01319a2a-6659-4a73-ba96-cdb81f4e01bd)
成功后记得保存api令牌密钥，记录下以下位置的账户ID,
![Image](https://github.com/user-attachments/assets/7ca33c12-ae87-438b-8bd1-d646894eb5f8)
接下来新建你的git仓库
完成后点击仓库设置，

![Image](https://github.com/user-attachments/assets/cc8d34d7-c0d3-494b-98d2-b4a61396a7ce)

添加两个密钥 
名称1 CLOUDFLARE_ACCOUNT_ID为workers-and-pages的ID
名称2 CLOUDFLARE_API_TOKEN为右上角新建的api令牌密钥。
完成后点击cloudflare页面的workers-and-pages页面 点击创建按钮，

![Image](https://github.com/user-attachments/assets/054d4bc4-e3ec-496e-adac-a2fb143943be)
添加构建配置为以下文本
![Image](https://github.com/user-attachments/assets/107b5b98-9643-4765-9307-b6fd60da71c7)

添加完成后在本地的vitepress配置一个G:\vitepress\.github\workflows\deploy.yml文件
代码为以下代码  不需要更改。
```
name: vitepress
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.1

      - run: pnpm install
      - run: pnpm run docs:build
      - run: ls -la docs/.vitepress/dist  

      - name: Deploy to Workers
        uses: cloudflare/wrangler-action@3.0.0
        with:
          command: pages deploy ./docs/.vitepress/dist --project-name hestia-docs
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```
这里的版本号是cloudflare默认版本！使用高版本会部署错误，我研究了好久不知道怎么使用最新版本！
package.json的配置要和上面匹配
```
	"engines": {
		"node": ">=20.0.0",
		"pnpm": ">=8.7.1"
	},
```
本地配置的最新无所谓!我本地的版本node是22+  pnpm是10+ 只需要指定版本号即可！
其它好像最新版本没啥影响。

最后推送到git后应该会自动部署vitepress到cloudflare，
